version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
	volumes: /usr/local/db
  backend:
    image: backend
    restart: always
    ports:
      - 8080:8080